### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by ValentinK00** [ValentinK00/POAIS-project#1]
Создать базу данных в **`PHPMyAdmin`**.
Каждое подразделение имеет штатное расписание, в котором имеется перечень должностей. Каждая должность имеет **`название`, `краткое название`, `шифр`, `нижнюю и верхнюю границы разрядов единой тарифной сетки`** (от 1 до 18). 
Также о сотруднике необходимо хранить личные данные: **`ФИО`**, **`возраст`**, **`пол`**, **`семейное положение`**.

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3144047/otdel_kadrov.zip)

**Comment by ValentinK00** [comment]
Добавить таблицу Journal

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3147047/otdel_kadrov.zip)

**Comment by GGT322** [comment]
[classes.zip](https://github.com/ValentinK00/POAIS-project/files/3147244/classes.zip)
