### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by ValentinK00** [ValentinK00/POAIS-project#2]
Создание проекта

**Comment by GGT322** [comment]
[classes.zip](https://github.com/ValentinK00/POAIS-project/files/3147257/classes.zip)

**Comment by GGT322** [comment]
[classes.zip](https://github.com/ValentinK00/POAIS-project/files/3147455/classes.zip)

**Comment by ValentinK00** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3147495/otdel_kadrov.zip)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3147576/otdel_kadrov.zip)

**Comment by ValentinK00** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3147822/otdel_kadrov.zip)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3148328/otdel_kadrov.zip)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3148390/otdel_kadrov.zip)

**Comment by GGT322** [comment]
[save-role, view-role.zip](https://github.com/ValentinK00/POAIS-project/files/3148474/save-role.view-role.zip)

**Comment by ValentinK00** [comment]
[list+add role.zip](https://github.com/ValentinK00/POAIS-project/files/3148480/list%2Badd.role.zip)

**Comment by ValentinK00** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3153622/otdel_kadrov.zip)

Добавление пользователя в базу через форму (UserMap)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3156607/otdel_kadrov.zip)
Изменён list-otdel, list-role, RoleMap, OtdelMap, доработаны сейвы

**Comment by GGT322** [comment]
[shedule, sheduleMap.zip](https://github.com/ValentinK00/POAIS-project/files/3157108/shedule.sheduleMap.zip)

**Comment by ValentinK00** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3157104/otdel_kadrov.zip)
Schedule добавление + лист (без сейва)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3164795/otdel_kadrov.zip)
добавление расписания

**Comment by ValentinK00** [comment]
[header.zip](https://github.com/ValentinK00/POAIS-project/files/3164796/header.zip)
Локализованный header

**Comment by ValentinK00** [comment]
[role_count.zip](https://github.com/ValentinK00/POAIS-project/files/3164915/role_count.zip)
role_count fix

**Comment by GGT322** [comment]
[list-schedule, delete-schedule.zip](https://github.com/ValentinK00/POAIS-project/files/3164962/list-schedule.delete-schedule.zip)
удаление

**Comment by ValentinK00** [comment]
[journal.zip](https://github.com/ValentinK00/POAIS-project/files/3165252/journal.zip)
journal шаблоны

**Comment by GGT322** [comment]
[JournalMap.zip](https://github.com/ValentinK00/POAIS-project/files/3165256/JournalMap.zip)

**Comment by ValentinK00** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3168624/otdel_kadrov.zip)
Текущая версия (не работает изменение расписания)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3168737/otdel_kadrov.zip)

**Comment by GGT322** [comment]
[otdel_kadrov.zip](https://github.com/ValentinK00/POAIS-project/files/3168946/otdel_kadrov.zip)
Сделаны: Расписание, Пользователь, Должность, Подразделение.
Штатное расписание -сделано
Список сотрудников на заданную дату (ФИО, дата рождения), женского пола, (55 лет) в текущем году -сделано
